update script

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -62,15 +62,23 @@ jobs:
           # Extract the version from the latest tag
           latest_tag_version=$latest_tag
 
-          # Extract the version from Cargo.toml in the PR branch
-          pr_version=$(grep '^version' crates/sargon/Cargo.toml | sed 's/version = "\(.*\)"/\1/')
+          # Extract the version from both Cargo.toml in the PR branch
+          pr_version_sargon=$(grep '^version' crates/sargon/Cargo.toml | sed 's/version = "\(.*\)"/\1/')
+          pr_version_sargon_uniffi=$(grep '^version' crates/sargon-uniffi/Cargo.toml | sed 's/version = "\(.*\)"/\1/')
 
           echo "Latest tag version: $latest_tag_version"
-          echo "PR version: $pr_version"
+          echo "PR version sargon: $pr_version_sargon"
+		  echo "PR version sargon-uniffi: $pr_version_sargon_uniffi"
+		  
+		  # Check if sargon and sargon-uniffi versions match
+		  if [ "$pr_version_sargon" != "$pr_version_sargon_uniffi" ]; then
+			echo "Error: sargon version ($pr_version_sargon) does not match sargon-uniffi version ($pr_version_sargon_uniffi)."
+			exit 1
+		  fi
 
           # Split the versions into major, minor, and patch components
           IFS='.' read -r -a tag_version_parts <<< "$latest_tag_version"
-          IFS='.' read -r -a pr_version_parts <<< "$pr_version"
+          IFS='.' read -r -a pr_version_parts <<< "$pr_version_sargon"
 
           major_diff=$((pr_version_parts[0] - tag_version_parts[0]))
           minor_diff=$((pr_version_parts[1] - tag_version_parts[1]))
